{
 "title": "daily performance insights",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "profit daily",
   "type": "trend",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH\r\n  impressions_stats AS (SELECT date, sum(profit) AS profit_total FROM impressions GROUP BY date),\r\n  clicks_stats AS (SELECT date, sum(profit) AS profit_total FROM clicks GROUP BY date)\r\nSELECT\r\n  COALESCE(impressions_stats.date, clicks_stats.date) AS \"date\",\r\n  COALESCE(impressions_stats.profit_total, 0) AS \"impressions profit\",\r\n  COALESCE(clicks_stats.profit_total, 0) AS \"clicks profit\",\r\n  COALESCE(impressions_stats.profit_total, 0) + COALESCE(clicks_stats.profit_total, 0) AS \"total profit\"\r\nFROM impressions_stats\r\nFULL JOIN clicks_stats ON clicks_stats.date = impressions_stats.date\r\nORDER BY date ASC"
    }
   ]
  },
  {
   "title": "total stats",
   "type": "stat",
   "gridPos": { "h": 14, "w": 8, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with\r\n  impressions_stats AS (\r\n    SELECT\r\n      count(*) AS impressions_total_count, \r\n      sum(profit) AS impressions_total_profit\r\n    FROM impressions\r\n  ),\r\n  clicks_stats AS (\r\n    SELECT\r\n      count(*) AS clicks_total_count,\r\n      sum(profit) AS clicks_total_profit\r\n    FROM clicks\r\n  )\r\nSELECT\r\n  coalesce(impressions_total_profit, 0) + coalesce(clicks_total_profit, 0) AS \"total profit\",\r\n  coalesce(impressions_total_profit, 0) AS \"impressions total profit\",\r\n  coalesce(clicks_total_profit, 0) AS \"clicks total profit\",\r\n  coalesce(impressions_total_count, 0) AS \"impressions total count\",\r\n  coalesce(clicks_total_count, 0) AS \"clicks total count\",\r\n  CASE\r\n    WHEN coalesce(impressions_total_count, 0) != 0\r\n      THEN round((coalesce(clicks_total_count, 0)::double precision / coalesce(impressions_total_count, 0)::double precision * 100)::numeric, 2)\r\n    ELSE\r\n      0\r\n  END AS \"conversion\"\r\nFROM impressions_stats\r\nJOIN clicks_stats ON true"
    }
   ]
  },
  {
   "title": "impressions and clicks count daily",
   "type": "trend",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "WITH\r\n  impressions_counted AS (SELECT date, count(*) AS impressions_count FROM impressions GROUP BY date),\r\n  clicks_counted AS (SELECT date, count(*) AS clicks_count FROM clicks GROUP BY date)\r\nSELECT\r\n  COALESCE(impressions_counted.date, clicks_counted.date) AS \"date\",\r\n  COALESCE(impressions_count, 0) AS \"impressions count\",\r\n  COALESCE(clicks_count, 0) AS \"clicks count\"\r\nFROM impressions_counted\r\nFULL JOIN clicks_counted ON clicks_counted.date = impressions_counted.date\r\nORDER BY date ASC"
    }
   ]
  }
 ]
}