// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	models "advertising/advertising-service/internal/models"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MlScoresRepo is an autogenerated mock type for the MlScoresRepo type
type MlScoresRepo struct {
	mock.Mock
}

// UpsertMLScore provides a mock function with given fields: ctx, mlScore
func (_m *MlScoresRepo) UpsertMLScore(ctx context.Context, mlScore models.MLScore) error {
	ret := _m.Called(ctx, mlScore)

	if len(ret) == 0 {
		panic("no return value specified for UpsertMLScore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.MLScore) error); ok {
		r0 = rf(ctx, mlScore)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMlScoresRepo creates a new instance of MlScoresRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMlScoresRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MlScoresRepo {
	mock := &MlScoresRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
