// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	AdvanceDayOperation                  OperationName = "AdvanceDay"
	CreateCampaignOperation              OperationName = "CreateCampaign"
	DeleteCampaignOperation              OperationName = "DeleteCampaign"
	GenerateAdTextOperation              OperationName = "GenerateAdText"
	GetAdForClientOperation              OperationName = "GetAdForClient"
	GetAdvertiserByIdOperation           OperationName = "GetAdvertiserById"
	GetAdvertiserCampaignsStatsOperation OperationName = "GetAdvertiserCampaignsStats"
	GetAdvertiserDailyStatsOperation     OperationName = "GetAdvertiserDailyStats"
	GetCampaignOperation                 OperationName = "GetCampaign"
	GetCampaignDailyStatsOperation       OperationName = "GetCampaignDailyStats"
	GetCampaignStatsOperation            OperationName = "GetCampaignStats"
	GetClientByIdOperation               OperationName = "GetClientById"
	ListCampaignsOperation               OperationName = "ListCampaigns"
	ModerateAdTextOperation              OperationName = "ModerateAdText"
	RecordAdClickOperation               OperationName = "RecordAdClick"
	UpdateCampaignOperation              OperationName = "UpdateCampaign"
	UploadCampaignImageOperation         OperationName = "UploadCampaignImage"
	UpsertAdvertisersOperation           OperationName = "UpsertAdvertisers"
	UpsertClientsOperation               OperationName = "UpsertClients"
	UpsertMLScoreOperation               OperationName = "UpsertMLScore"
)
