// Code generated by ogen, DO NOT EDIT.
package api

type AdvanceDayRes interface {
	advanceDayRes()
}

type CreateCampaignRes interface {
	createCampaignRes()
}

type DeleteCampaignRes interface {
	deleteCampaignRes()
}

type GenerateAdTextRes interface {
	generateAdTextRes()
}

type GetAdForClientRes interface {
	getAdForClientRes()
}

type GetAdvertiserByIdRes interface {
	getAdvertiserByIdRes()
}

type GetAdvertiserCampaignsStatsRes interface {
	getAdvertiserCampaignsStatsRes()
}

type GetAdvertiserDailyStatsRes interface {
	getAdvertiserDailyStatsRes()
}

type GetCampaignDailyStatsRes interface {
	getCampaignDailyStatsRes()
}

type GetCampaignRes interface {
	getCampaignRes()
}

type GetCampaignStatsRes interface {
	getCampaignStatsRes()
}

type GetClientByIdRes interface {
	getClientByIdRes()
}

type ListCampaignsRes interface {
	listCampaignsRes()
}

type ModerateAdTextRes interface {
	moderateAdTextRes()
}

type RecordAdClickRes interface {
	recordAdClickRes()
}

type UpdateCampaignRes interface {
	updateCampaignRes()
}

type UploadCampaignImageReq interface {
	uploadCampaignImageReq()
}

type UploadCampaignImageRes interface {
	uploadCampaignImageRes()
}

type UpsertAdvertisersRes interface {
	upsertAdvertisersRes()
}

type UpsertClientsRes interface {
	upsertClientsRes()
}

type UpsertMLScoreRes interface {
	upsertMLScoreRes()
}
